-- phpMyAdmin SQL Dump
-- version 4.9.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le :  Dim 01 mai 2022 à 20:04
-- Version du serveur :  10.4.8-MariaDB
-- Version de PHP :  7.3.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

--
-- Base de données :  `pixy`
--

-- --------------------------------------------------------

--
-- Structure de la table `comment`
--

CREATE TABLE `comment` (
  `id` int(11) NOT NULL,
  `description` text NOT NULL,
  `author` varchar(255) NOT NULL,
  `mark` int(11) NOT NULL,
  `product_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Structure de la table `order`
--

CREATE TABLE `order` (
  `id` int(11) NOT NULL,
  `first_name` varchar(255) NOT NULL,
  `last_name` varchar(255) NOT NULL,
  `total` float NOT NULL,
  `uid` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Déchargement des données de la table `order`
--

INSERT INTO `order` (`id`, `first_name`, `last_name`, `total`, `uid`) VALUES
(1, 'Laura', 'Dehours', 10, '62409604aca79'),
(2, 'Laura', 'Dehours', 10, '624099677febf'),
(3, 'Laura', 'Dehours', 10, '62409b1ce0652'),
(4, 'Laura', 'Dehours', 9000, '62409b8063171');

-- --------------------------------------------------------

--
-- Structure de la table `product`
--

CREATE TABLE `product` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `image` varchar(255) NOT NULL,
  `price` decimal(10,0) NOT NULL,
  `short_description` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Déchargement des données de la table `product`
--

INSERT INTO `product` (`id`, `title`, `description`, `image`, `price`, `short_description`) VALUES
(1, 'Kodak', 'Appareil photo numérique \r\n- Zoom optique 42X \r\n- Grand angle 24 mm \r\n- 16 mégapixels \r\n- Écran LCD 3\'\' \r\n- Vidéo HD 720 p \r\n- Stabilisation optique de l\'image \r\n- Batterie lithium-ion', 'assets\\images\\camera1.jpg', '3000', 'Test de description courte'),
(12, 'Fujitsu', '- Appareil photo numérique à visée et prise de vue avec des fonctions riches.\r\n\r\n- Écran LCD TFT 2,8 \", photos 16MP et vidéos FHD 1080p, batterie 1050 mah (fonctionne environ 2-3 heures après une charge complète).\r\n\r\n- Caméra numérique étanche pour enfants, jusqu\'à une profondeur maximale de 16FT / 5M sous l\'eau. \r\n\r\n- Conception compacte, aucun boîtier supplémentaire n\'est nécessaire. Caméra sous-marine parfaite pour la natation, la plongée en apnée, la plongée. Profitez de l\'été, capturez le temps amusant de l\'eau des enfants.\r\n\r\n- Conception légère et appareil photo étanche de petite taille, facile à utiliser. \r\nIl est portable pour prendre des photos pour des moments heureux.\r\n\r\nAppareil photo débutant pour enfants, adolescents, étudiants, personnes âgées. Grand cadeau pour eux d\'explorer le monde avec un appareil photo. Pour les amateurs uniquement, pas pour les utilisateurs professionnels.\r\n\r\n- Cette caméra étanche nécessite jusqu\'à 32 Go de carte Micro SD externe (non incluse).', 'assets\\images\\camera2.jpg', '3000', ''),
(13, 'Canon', '- Appareil photo numérique multifonctionnel: \r\nLe flash intégré de la caméra vidéo peut être ouvert ou masqué en fonction de la scène, et vous pouvez facilement changer de mode si nécessaire. \r\nCet appareil photo compact possède de nombreuses fonctions, notamment Selfie, prise de vue en continu, coupure du son à l\'aide d\'un seul bouton, balance des blancs, horodatage et DISP.\r\n\r\n- Objectif d\'appareil photo: professionnel et équipement radio. \r\nNous équipons l\'appareil photo d\'un objectif grand angle professionnel détachable de 52 mm et d\'un objectif macro, de sorte que l\'appareil photo est idéal pour capturer facilement un large champ de vision, et l\'objectif macro capture la diversité du monde minuscule . \r\nÉquipé d\'un microphone externe, le son de la vidéo est plus clair.\r\n\r\n- Caméra PC et sortie HDMI: \r\nLa caméra peut être connectée au PC via un câble USB. \r\nVous pouvez ensuite sélectionner \"Mode de stockage de masse\" pour transférer des fichiers sur votre ordinateur ou sélectionner \"Caméra PC\" pour l\'utiliser comme caméra PC pour profiter de chats vidéo ou de diffusion en direct. \r\nSi vous souhaitez lire la vidéo que vous avez tournée, vous pouvez vous connecter directement à votre téléviseur HD à l\'aide d\'un câble HDMI (câble HDMI non inclus).\r\n\r\n- Fonction Pause Et Enregistrement Pendant La Charge :\r\nCet appareil photo numérique 4k dispose d\'une excellente fonction de pause qui vous permet de continuer à enregistrer dans le même fichier sans redémarrer un nouveau fichier. Appuyez simplement sur le bouton d\'alimentation de la caméra pour mettre en pause ou redémarrer l\'enregistrement. Cette caméra vidéo numérique dispose d\'une batterie Li-Ion de 1500 mAh qui prend en charge l\'enregistrement pendant la charge\r\n\r\n- Meilleur choix pour les amateurs:\r\nVous obtiendrez un appareil photo numérique 4K * 1, un objectif de caméra professionnel * 1, un microphone vidéo * 1, une carte SD 32 Go * 1, un sac photo portable * 1 en même temps. \r\n\r\nCet appareil photo est parfait pour les utilisateurs débutants et constitue un excellent cadeau pour les débutants. \r\nNous soutenons la garantie de 1 an. Si vous avez des questions, n\'hésitez pas à nous contacter, nous vous fournirons la meilleure solution dans les 24 heures.', 'assets\\images\\camera3.jpg', '3000', ''),
(14, 'Samsung', '- Le logiciel le plus récent, vient d\'être mis à jour! Les utilisations nombreuses cet appareil photo numérique: images fixes numériques, Web Cam, lecture et enregistrement des vidéos, enregistrement vocal et plusieurs d\'autres.\r\n\r\n- Écran LCD TFT de 2,7 pouces pour une vidéo de couleurs vives, batterie rechargeable Lithium Ion (Li-Ion) de 550 mAh permet l\'enregistrement vidéo continu jusqu\'à 60 minutes. \r\n\r\n- Dans le coffret de l\'appareil photo vous trouverez deux batteries, mais il en souffit une pour le fonctionnement de l\'appareil, la deuxième est de recharge.\r\n\r\n- Résolution de 21 méga pixels pour la meilleure prise de vue, résolution HD 720P pour l\'enregistrement vidéo, créez votre chef-d\'œuvre HD! \r\n\r\n- L\'appareil photo est compatible avec les cartes mémoire externe de 64 Go maximum. \r\nLa carte mémoire n\'est pas fournie. \r\nLa carte SD doit être formatée avant de l\'utiliser.\r\n\r\n- Mode Stabilisé, Détection des visages, Prise de vue en continu, Retardateur, Zoom numérique 8x, Logiciel PhoTags Express pour l\'édition de photos, l\'impression et le partage avec des e-mails etc.\r\n\r\n- Garantie de non-satisfaction d\'un mois contre remboursement et garantie de qualité d\'un an.', 'assets\\images\\camera4.jpg', '3000', ''),
(15, 'Apple', '- Appareil photo numérique haute résolution 4K 48MP: \r\nCet appareil photo numérique peut enregistrer des vidéos de résolution jusqu\'à 4K / 30 FPS et des images de 48,0 mégapixels. \r\nCette caméra de vlog prend également en charge le zoom avant ou le zoom arrière 16x. \r\nIl est équipé d\'un objectif grand angle 0.45X52mm, d\'un objectif macro et d\'une carte mémoire 32G. \r\nCet appareil photo est conçu pour que les débutants profitent du charme de la photographie.\r\n\r\n- Appareil photo numérique multifonctionnel: \r\nLe flash intégré de la caméra vidéo peut être ouvert ou masqué en fonction de la scène, et vous pouvez facilement changer de mode si nécessaire. \r\nCet appareil photo compact possède de nombreuses fonctions, notamment Selfie, prise de vue en continu, coupure du son à l\'aide d\'un seul bouton, balance des blancs, horodatage et DISP.\r\n\r\n- Enregistrement pendant le chargement: L\'appareil photo est équipé d\'une batterie rechargeable au lithium-ion de 1500 mAh. La mini caméra prend également en charge l\'enregistrement pendant la charge, ce qui est très approprié pour la prise de vue à long terme. \r\nLes modes photo et vidéo ont également 8 sélections de scènes et 16 effets de filtre intéressants. \r\nVous pouvez choisir votre scène ou effet photo préféré avant de prendre une photo.\r\n\r\n- Fonction microphone et webcam intégrés: \r\nCet appareil photo numérique dispose d\'un microphone et d\'un haut-parleur intégrés. \r\nEn connectant cet appareil photo bon marché à un ordinateur, il peut être utilisé comme webcam. Un câble micro USB est inclus dans l\'emballage, qui peut être connecté à un ordinateur portable pour une diffusion directe sur YouTube ou Facebook. \r\nAprès avoir importé les images et vidéos capturées sur l\'ordinateur, vous obtiendrez une image plus claire.\r\n\r\n- Le cadeau parfait et l\'assurance qualité: \r\nCet appareil photo pour débutants est très facile à utiliser et compact, pratique pour les voyages et une utilisation quotidienne. \r\nCet appareil photo compact est un cadeau idéal pour les adultes, les personnes âgées, les étudiants, les enfants et les débutants.\r\n\r\n- Nous offrons une garantie d\'un an pour cette caméra de blog.', 'assets\\images\\camera5.jpg', '3000', ''),
(16, 'Huawei', 'Le logiciel le plus récent, vient d\'être mis à jour! Les utilisations nombreuses cet appareil photo numérique: images fixes numériques, Web Cam, lecture et enregistrement des vidéos, enregistrement vocal et plusieurs d\'autres.\r\n\r\n- Écran LCD TFT de 2,7 pouces pour une vidéo de couleurs vives, batterie rechargeable Lithium Ion (Li-Ion) de 550 mAh permet l\'enregistrement vidéo continu jusqu\'à 60 minutes. \r\n\r\n- Dans le coffret de l\'appareil photo vous trouverez deux batteries, mais il en souffit une pour le fonctionnement de l\'appareil, la deuxième est de recharge.\r\n\r\n- Résolution de 21 méga pixels pour la meilleure prise de vue, résolution HD 720P pour l\'enregistrement vidéo, créez votre chef-d\'œuvre HD! L\'appareil photo est compatible avec les cartes mémoire externe de 64 Go maximum. \r\n\r\n- La carte mémoire n\'est pas fournie. \r\nLa carte SD doit être formatée avant de l\'utiliser.\r\n\r\n- Mode Stabilisé, Détection des visages, Prise de vue en continu, Retardateur, Zoom numérique 8x, Logiciel PhoTags Express pour l\'édition de photos, l\'impression et le partage avec des e-mails etc.\r\n\r\n- Garantie de non-satisfaction d\'un mois contre remboursement et garantie de qualité d\'un an.', 'assets\\images\\camera6.jpg', '3000', ''),
(17, 'Yashica', '- Caméra Vlogging HD 48MP & 4.0K:\r\nLa caméra vlogging prend en charge la résolution vidéo 4.0K FHD/30pfs et prend des photos avec une résolution d\'image 48MP. \r\nIl peut obtenir d\'excellents effets de photographie et d\'enregistrement. \r\nEnregistrer des vidéos de très haute qualité et capturer des moments merveilleux, obtenir une qualité d\'image plus naturelle et réaliste.\r\n\r\n- 3.0 \'\' Flip LED Screen 180° Rotation: Cet appareil photo numérique a un écran LCD de 3 pouces, l\'écran peut également être tourné à 180 °, vous pouvez prendre d\'autres choses, mais aussi Selfie, ce qui rend la prise de selfie plus facile et plus amusante. \r\nL\'appareil photo numérique dispose également d\'une fonction anti-tremblement pour prendre des photos claires pour vous. Il existe également plusieurs modes de prise de vue tels que la vidéo accélérée et la vidéo au ralenti.\r\n\r\n- Grand angle: \r\nL\'appareil photo numérique dispose d\'un zoom numérique 16x et peut facilement filmer des paysages éloignés. \r\nCette caméra vidéo est livrée avec un objectif grand angle, vous pouvez utiliser l\'objectif grand angle pour un plus large éventail de paysages.\r\nConception d\'objectif grand angle, idéale pour des images époustouflantes, parfaite pour la prise de vue en extérieur.\r\n\r\n- Fonction WIFI et Webcam: \r\nL\'appareil photo numérique WiFi prend en charge la prise de photos et la prise de vidéos via votre smartphone. \r\nVous permet de partager des photos et des vidéos sur les réseaux sociaux la première fois. \r\nEt vous pouvez également le prendre comme webcam en choisissant le \"mode caméra\" afin de profiter du chat vidéo ou de la diffusion en direct.\r\n\r\n- Meilleur choix pour les amateurs: \r\nCet appareil photo numérique est d\'apparence rétro, léger et portable, adapté à diverses occasions. Nous vous assurerons un service après-vente de qualité. \r\n\r\nSi vous avez des questions, veuillez nous contacter à tout moment. Conseils chaleureux : \r\n(1) Le caméscope est conçu pour les amateurs, pas pour la photographie professionnelle. \r\n(2) Avant d\'utiliser l\'appareil photo, veuillez formater la carte SD fournie avec l\'appareil photo.', 'assets\\images\\camera7.jpg', '3000', ''),
(18, 'Dell', '- Image de 5,6 millions de pixels, vidéo de 4K Améliorée à une résolution plus élevée, cette appareil photo etanche peut prendre des photos au format JPEG de haute qualité de 48 millions de pixels. \r\nAvec l\'option de résolution vidéo 4,0K, vous pouvez enregistrer de manière vivante vos moments sympas au format AVI. \r\n\r\n- Le zoom numérique 18x permet à l\'appareil photo étanche de capturer des moments précieux de près, de loin et entre les deux.\r\n\r\n- 10 pieds étanche Cette appareil photo étanche est complètement scellée à des fins d\'étanchéité. \r\nIl peut plonger à 10 pieds à chaque fois pendant une heure à la fois sans étui supplémentaire. \r\nLa dragonne garantit que vous ne perdrez pas l\'appareil photo étanche pendant la plongée en apnée, la natation ou le rafting. \r\n\r\n- La fonction anti-tremblement intégrée avancée fournit des photos stables et fluides.\r\n\r\n- Double écran, selfie:\r\nCet appareil photo étanche équipé d\'un écran double écran avant de 2 pouces et d\'un écran arrière de 3,0 pouces, il peut facilement prendre un selfie en appuyant sur le bouton de commutation de l\'écran. \r\nAvec le Selfie 2/5 / 10s, personne ne manquera dans les photos de groupe! Cette appareil photo étanche prend en charge une carte micro SD jusqu\'à 128G (non incluse dans l\'emballage).\r\n\r\n- Prise de vue en continu, charge pendant l\'enregistrement:\r\nSélectionnez le mode de prise de vue en continu pour commencer à prendre plusieurs photos en peu de temps. \r\nCet appareil photo est équipé d\'un flash LED, qui peut être allumé en appuyant sur le bouton «Flash». \r\nNotre appareil photo étanche de plongée en apnée prend en charge la charge ou l\'alimentation mobile lors de l\'enregistrement. \r\nPas besoin de s\'inquiéter de l\'arrêt.\r\n\r\n- Vous obtiendrez 1700mAh La batterie au lithium-ion, le sac pour appareil photo, le manuel d\'utilisation, la dragonne, le câble USB et l\'adaptateur sont inclus dans l\'emballage. \r\n\r\nSi vous rencontrez des problèmes avec votre appareil photo étanche dans un délai d\'un an à compter de la date d\'achat, veuillez nous contacter et nous serons heureux de le résoudre pour vous.', 'assets\\images\\camera8.jpg', '3000', ''),
(19, 'Fujifilm', '- FHD 1080P & 36MP Appareil Photo Numérique:\r\nCet appareil photo numérique a une résolution d\'image HD 1080P et une résolution vidéo de 36MP, a d\'excellentes performances d\'enregistrement et de photographie, vous pouvez l\'utiliser pour enregistrer les moments les plus importants à tout moment. \r\nLa caméra est livrée avec une carte SD de 32 Go, pas besoin d\'achat supplémentaire. \r\n\r\n- Veuillez noter que la carte SD doit être formatée avant utilisation.\r\n\r\n- Zoom Numérique 16X & Écran LCD IPS 2,4\":\r\nCet appareil photo est équipé d\'un zoom numérique 16X, qui a la capacité de zoomer sur les images que vous avez capturées, vous pouvez facilement voir des objets éloignés. \r\nCet appareil photo adopte un écran LCD IPS de 2,4 pouces, qui peut prendre ou lire des images/vidéos avec une qualité claire. \r\nInterface de trépied externe, vous pouvez installer un trépied pour vous aider à stabiliser la prise de vue.\r\n\r\n- Appareil Photo Numérique Léger:\r\nCet appareil photo numérique est de petite taille et léger (seulement 0,5 lb). \r\nVous pouvez le porter avec une lanière ou le mettre facilement dans votre poche ou votre sac à dos, ce deviendra votre meilleur compagnon. \r\nCet appareil photo est puissant et prend en charge la capture de sourire, détection facial, anti-vibrations, prise de vue en continu, fonctions selfie. \r\nLa lumière d\'appoint intégrée vous aide à prendre des photos de haute qualité dans l\'obscurité.\r\n\r\n- Enregistrement de Webcam & Batterie Améliorée:\r\nCet appareil photo numérique peut être utilisé comme webcam. \r\nConnectez l\'appareil photo à l\'ordinateur via un câble USB pour passer des appels vidéo avec votre famille ou vos amis. \r\nCet appareil photo est livré avec deux batteries lithium-ion rechargeables de 700mAh 3,7V, a une plus longue durée de vie de la batterie et est pratique pour vous de remplacer la batterie et de garder l\'appareil photo sous tension à tout moment.\r\n\r\n- Cadeau Parfait:\r\nCet appareil photo numérique a une apparence à la mode et un boîtier compact, c\'est un excellent choix pour les enfants, les adolescents, les débutants et les personnes âgées. \r\nFacile à utiliser et adapté à un usage quotidien et aux voyages.', 'assets\\images\\camera9.jpg', '3000', ''),
(20, 'Sony', '- Caméra étanche 1080P et 30MP: \r\nCette appareil photo etanche  récemment mise à niveau prend en charge la vidéo 1080P et les photos 30MP avec un zoom numérique jusqu\'à 16x. \r\nIl peut vous aider à capturer des photos plus merveilleuses et réelles. \r\n\r\n- Cette caméra haute définition 1080P peut donner vie à vos vidéos en capturant vos moments préférés avec une qualité incroyable. C\'est le choix parfait pour les photographes débutants.\r\n\r\n- Écran TFT de 2,7 pouces et anti-secousse: La appareil photo etanche est équipée d\'un écran couleur de haute qualité de 2,7 pouces. \r\n\r\n- Technologie de reconnaissance faciale unique qui capture votre précieux moment de jeu. \r\nUn anti-shake rend vos photos plus claires. Vous ne manquerez plus aucune action passionnante. Profitez de votre temps de tournage.\r\n\r\n- 6 Prise de vue en continu à vitesse rapide: \r\nCet appareil photo etanche dispose d\'une fonction de flash et de 6 fonctions de prise de vue en continu. \r\nVous pouvez également prendre des selfies et prendre des photos en rafale. Avec la prise en charge du flash, cet appareil photo étanche peut vous aider à prendre de superbes photos même dans des environnements sombres. \r\nAinsi, vous ne manquerez aucun moment précieux.\r\n\r\n- Caméra sous-marine 10FT: La fonction étanche permet à cet appareil photo numérique d\'être immergé à 10 pieds sous l\'eau sans boîtier étanche. \r\nVous pouvez l\'apporter à la plongée, au camping, à l\'escalade et à toute autre activité. \r\nPour le prendre et vous ne manquerez aucun paysage que vous souhaitez enregistrer.\r\n\r\n- Portable et facile à utiliser:Cet appareil photo étanche avec une conception d\'apparence légère et portable. Notre appareil photo numérique point & shoot convient à la plupart des endroits de votre vie quotidienne. \r\n\r\n- Il prend également en charge l\'enregistrement pendant la charge, vous n\'avez pas à vous soucier de la mise hors tension de la batterie pendant votre voyage.', 'assets\\images\\camera10.jpg', '3000', ''),
(21, 'Nikon', 'Résolution vidéo:\r\nFull HD : 1920 x 1080 60i (59,94 vues/s), 50i (50 vues/s), 1920 x 1080 30p (progressif) 25p, 24p; HD : 1280 x 720 60p, 50p; SD : 640 x 424 30p, 25p.\r\n\r\nMicro SD\r\n\r\nFormat d\'image:\r\nJPEG (Exif 2.3), NEF (RAW) 14 bits, compressé, NEF + JPEG.\r\n\r\nRésolution de l\'écran:\r\n921 000\r\n\r\nTaille d\'écran en cm:\r\n7,6 cm', 'assets\\images\\camera11.jpg', '3000', ''),
(22, 'Lumix', '- Double stabilisateur d\'image sur 5 axes (Dual IS 2)\r\n- Stabilisation d\'image\r\n- Résiste à la poussière / aux éclaboussures\r\n- Boîtier avant en alliage de magnésium\r\n- Aide à la mise au point (Focus Peaking) / Contrôle de l\'éclairage et des ombres\r\n- Vidéo 4K, fonction « Post Focus », fonction « Focus Stacking »', 'assets\\images\\camera12.jpg', '3000', ''),
(23, 'Reflex', 'Résolution vidéo:\r\nFull HD : 1920 x 1080 30i (progressif), 25i/24i (fine); HD : 1280 x 720 60i/50i (fine); SD : 640 x 424 30i/25i (fine)\r\n\r\nFormat d\'image:\r\nJPEG, NEF 12 bits (RAW)\r\n\r\nRésolution de l\'écran:\r\n921 000\r\n\r\nTaille d\'écran en cm:\r\n7,6 cm', 'assets\\images\\camera13.jpg', '3000', ''),
(24, 'Bridge', '- Caméscope Ultra HD 4K:\r\nRésolution d\'image de haute qualité jusqu\'à 48MP, résolution vidéo 4K 3840x2160 (30FPS) vous apporte des photos et des vidéos en haute définition avec une qualité d\'image sans perte pour vraiment restaurer vos moments merveilleux.\r\nCaméra vidéo à zoom numérique 16X pour vous aider à voir les petits détails.\r\n\r\n- WIFI Vlogging Camera:\r\nVous pouvez capturer, partager ou sauvegarder vos belles photos ou vidéos. Transformez votre smartphone ou votre tablette en télécommande en temps réel pour contrôler la caméra vidéo via une connexion WiFi. \r\nN\'hésitez pas à partager vos excellentes photos et vidéos avec Facebook, YouTube et autres médias sociaux.\r\n\r\n- Objectif d\'appareil photo professionnel et équipement radio: Équipé d\'un objectif grand angle amovible à 120 degrés, cet appareil photo numérique a une plage de prise de vue plus large. \r\nL\'objectif macro 0,01M permet de révéler pleinement les moindres détails lors de la prise de vue à courte distance. Équipé d\'un microphone externe pour un son vidéo plus clair.\r\n\r\n- Appareil photo compact multifonctionnel: \r\nCet appareil photo numérique dispose d\'un écran ultra haute définition de 3,0 pouces. \r\nL\'écran peut être retourné pour des selfies faciles. Prise en charge de l\'enregistrement en boucle, de la pause vidéo, de l\'enregistrement silencieux, du retard, du ralenti, du selfie, de la prise de vue en continu, de la prise de vue à intervalles, de la lumière d\'appoint vidéo, du flash et des fonctions DISP.\r\n\r\n- Ce que vous obtiendrez:\r\nVous recevrez un appareil photo numérique 4K * 1, un objectif d\'appareil photo professionnel * 1, un microphone vidéo * 1, une carte SD de 32 Go * 1, un sac pour appareil photo portable * 1 en même temps. \r\n\r\n- Nous offrons un service de retour et d\'échange gratuit pendant 2 mois. \r\nSi vous avez des questions sur l\'utilisation de votre appareil photo numérique, n\'hésitez pas à nous contacter.', 'assets\\images\\camera14.jpg', '3000', ''),
(25, 'Minolta', '- HD 1080P & 36MP:\r\nCet appareil photo numérique a une résolution d\'image HD 1080P et une résolution vidéo de 36MP, et un microphone intégré peut vous aider à prendre des images ou des vidéos claires et à capturer des moments passionnants et inoubliables. \r\nRépondez pleinement à vos besoins, vous pouvez profiter d\'un bon moment entre amis, famille et camarades de classe.\r\n\r\n- Enregistrement de webcam & vlogging:\r\nCet appareil photo numérique peut être utilisé comme webcam. \r\nÉteignez d\'abord l\'appareil photo, connectez l\'appareil photo à l\'ordinateur avec un câble USB, appuyez simultanément sur le bouton d\'alimentation et le bouton MODE pour passer en mode webcam, puis vous pouvez passer un appel vidéo. \r\nVous pouvez également transférer les fichiers de l\'appareil photo sur l\'ordinateur, puis partager vos photos et vidéos sur Facebook, YouTube et d\'autres médias sociaux.\r\n\r\n- Zoom Numérique 16X & Fonction de Pause:\r\nCet appareil photo numérique prend en charge le zoom numérique 16x, qui peut agrandir les images et les vidéos. \r\nIl dispose également d\'une fonction de pause, qui peut être mise en pause lors de l\'enregistrement ou de la lecture de la vidéo. \r\nLa lumière d\'appoint intégrée vous aide à prendre des photos de haute qualité dans l\'obscurité. \r\nInterface de trépied externe, vous pouvez installer un trépied pour vous aider à stabiliser la prise de vue.\r\n\r\n- Portable & Facile à Utiliser:\r\nCe mini appareil photo numérique portable est très léger et petit, plus petit qu\'un smartphone, vous pouvez facilement le mettre dans votre poche et le transporter à tout moment, n\'importe où. \r\nCet appareil photo numérique à viser et à photographier est très facile à utiliser et simple à contrôler, très adapté aux personnes âgées, aux adolescents, aux enfants et aux étudiants.\r\n\r\n- Multifonctionnel & Meilleur Cadeau: Cette mini caméra prend en charge les fonctions Beauté visage, anti-tremblement, détection de visage, capture de sourire et minuterie Selfie. Cet appareil photo est le meilleur cadeau pour les grands-parents, les pères, les mères, les adolescents, les enfants et les étudiants, que ce soit la fête des mères, la fête des pères, le jour de Thanksgiving, l\'anniversaire et Noël.', 'assets\\images\\camera15.jpg', '3000', ''),
(26, 'Lithium', '- Appareil photo numérique 1080P et 30 MP:\r\nLa résolution vidéo de la appareil photo numérique est de 1080P et l\'image prend en charge jusqu\'à 30MP. \r\nVous pouvez facilement basculer entre le mode vidéo et le mode image en appuyant sur le bouton de commutation. \r\nUne qualité d\'image claire est suffisante pour vos besoins de prise de vue quotidiens.\r\n\r\n- Zoom numérique 8X:\r\nCet appareil photo numérique compact dispose d\'un zoom numérique 8x vous offrant une vue fantastique sur le paysage au loin.\r\nLa conception compacte, légère et de poche rend cet appareil photo numérique facile à transporter partout. \r\nNotre appareil photo numérique pas cher prend en charge la carte SD jusqu\'à 128 Go (Une carte SD de 32 Go est incluse dans l\'emballage.).\r\n\r\n- Écran de 2,7 pouces et facile à utiliser:\r\nL\'appareil photo équipé d\'un écran haute définition TFT de 2,7 pouces peut être utilisé pour parcourir le menu, ce qui le rend facile à utiliser et à réaliser de bonnes œuvres. \r\nIl s\'agit d\'un appareil photo numerique ordinaire d\'entrée de gamme économique, facile à utiliser, adapté à un usage novice / étudiant / domestique, et peut également être utilisé comme cadeau.\r\n\r\n- Appareil multifonction:\r\nCet appareil photo compact numérique avec un miroir selfie facilite le selfie. \r\nLes flashs offrent la meilleure solution lorsque vous rencontrez des problèmes pour prendre des photos dans des conditions de faible luminosité. \r\nCet appareil photo a un mode anti-tremblement pour rendre vos photos plus claires. \r\nL\'appareil photo a une fonction de prise de vue continue de trois secondes pour capturer un moment merveilleux.\r\n\r\n- Appareil photo rechargeable et conseils:\r\nL\'appareil photo est équipé de deux batteries rechargeables de 750 mAh. \r\nLe câble USB prend non seulement en charge la charge, mais prend également en charge le transfert de photos et de vidéos de l\'appareil photo vers votre ordinateur pour enregistrer et collecter des photos en temps opportun. \r\nSi vous avez des questions, notre équipe de service à la clientèle vous aidera. J\'espère que la caméra vous apportera une bonne expérience.', 'assets\\images\\camera16.jpg', '3000', ''),
(27, 'Camera', 'Image HD:\r\nL\'appareil photo numérique prend en charge la prise de vue photo 24MP, le zoom numérique 18X, l\'enregistrement vidéo haute définition, l\'enregistrement de la vie merveilleuse.\r\n\r\n- Écran TFT-LCD 3,0 pouces:\r\nAvec un écran LCD HD 3 pouces, il vous fournit des images claires, ce qui est pratique pour le réglage de la composition et les paramètres pour perfectionner l\'image.\r\n\r\n- Flash Light:\r\nLe flash intégré peut être utilisé pour la prise de photos normale même dans un environnement sombre, le port USB est pratique pour le chargement.\r\n\r\n- Longue durée de service:\r\nLa batterie de grande capacité de 1500 mAh dure longtemps, petite et légère, ce qui convient parfaitement aux réunions de famille et aux voyages en plein air.\r\n\r\n- Service après-vente:\r\nSi vous avez des questions sur le produit, n\'hésitez pas à nous contacter, nous vous répondrons dans les 24 heures pour vous assurer que vous êtes satisfait à 100%.', 'assets\\images\\camera17.jpg', '3000', ''),
(28, 'Yokai', '- Appareil photo numérique 2,7K avec écran rabattable:\r\nL\'appareil photo numérique prend en charge une résolution vidéo de 2,7K et une résolution d\'image de 30MP avec une bonne qualité d\'image. \r\nL\'appareil photo numerique prend également en charge le zoom numérique 4x, ce qui signifie que vous pouvez zoomer ou dézoomer sur l\'image pour une meilleure capture des détails.\r\n\r\n- Fonction webcam et transfert facile vers un PC:\r\nCet appareil photo numerique prend en charge la fonction webcam, connectez l\'ordinateur via USB pour sélectionner l\'option webcam pour utiliser la webcam. Avec ces fonctionnalités, ces appareil photo compact peuvent diffuser une image ou une vidéo en temps réel sur l\'ordinateur. \r\nIl est facile de transférer les fichiers vidéo ou image sur votre ordinateur Windows ou MAC via le câble USB inclus dans l\'emballage.\r\n\r\n- Appareil photo numérique multifonctionnel:\r\nCette appareil photo compact était équipée d\'un flash intégré rétractable, vous pouvez l\'utiliser pour obtenir un champ de vision plus lumineux de votre photo simplement en l\'ouvrant lorsque la vision est limitée dans des environnements sombres. \r\nLes caméras pour débutants de moins de 100 ans prennent en charge la détection des tremblements et des visages, la détection des sourires, la prise de vue en temps (2s et 10s), la prise de vue en continu, etc.\r\n\r\n- Batterie rechargeable de 800 mAh et carte Micro SD de 32 Go gratuite:\r\nLes appareils photos numériques compacts les plus achetés sont légers et faciles à transporter. \r\nCette caméra pour youtube est équipée de deux batteries rechargeables (800 mAh).\r\nCet camera prend en charge les cartes Micro SD jusqu\'à 128 Go (la classe 10 est recommandée), et vous obtiendrez une carte Micro SD de 32 Go gratuite si vous achetez notre appareil photo.\r\n\r\n- Cadeau parfait pour débutant:\r\nCet appareil photo numerique bon marché est parfait pour les utilisateurs débutants et fera un cadeau génial pour les débutants. \r\nCet appareil photo a un look exquis. \r\nIl est non seulement léger mais aussi portable. \r\nL\'enregistrement de voyages, d\'événements sportifs, de mariages, d\'anniversaires et d\'autres activités sera si facile avec son aide.', 'assets\\images\\camera18.jpg', '3000', ''),
(29, 'Watch', '- Caméscope Ultra HD 4:\r\nRésolution d\'image de haute qualité jusqu\'à 48MP, résolution vidéo 4K 3840x2160 (30FPS) vous apporte des photos et des vidéos en haute définition avec une qualité d\'image sans perte pour vraiment restaurer vos moments merveilleux. \r\nCaméra vidéo à zoom numérique 16X pour vous aider à voir les petits détails.\r\n\r\n- 3.0 \'\' Flip LED Screen 180° Rotation: Cet appareil photo numérique a un écran LCD de 3 pouces, l\'écran peut également être tourné à 180 °, vous pouvez prendre d\'autres choses, mais aussi Selfie, ce qui rend la prise de selfie plus facile et plus amusante. \r\nL\'appareil photo numérique dispose également d\'une fonction anti-tremblement pour prendre des photos claires pour vous. \r\nIl existe également plusieurs modes de prise de vue tels que la vidéo accélérée et la vidéo au ralenti.\r\n\r\n- Zoom numérique 16x et objectif grand angle:\r\nL\'appareil photo numérique dispose d\'un zoom numérique 16x et peut facilement filmer des paysages éloignés. \r\nCette caméra vidéo est livrée avec un objectif grand angle, vous pouvez utiliser l\'objectif grand angle pour un plus large éventail de paysages. Conception d\'objectif grand angle, idéale pour des images époustouflantes, parfaite pour la prise de vue en extérieur.\r\n\r\n- Fonction WIFI et Webcam:\r\nL\'appareil photo numérique WiFi prend en charge la prise de photos et la prise de vidéos via votre smartphone.\r\n\r\nTéléchargez simplement l\'application \"XDV PRO\" en scannant le code QR ou en recherchant sur Google ou App Store, vous pouvez contrôler à distance l\'appareil photo pour prendre des photos et obtenir immédiatement les photos dans l\'appareil photo. \r\nVous permet de partager des photos et des vidéos sur les réseaux sociaux la première fois.\r\n\r\n- Meilleur choix pour les amateurs: \r\nCet appareil photo numérique est d\'apparence rétro, léger et portable, adapté à diverses occasions. \r\nNous vous assurerons un service après-vente de qualité. \r\n\r\nSi vous avez des questions, veuillez nous contacter à tout moment. Conseils chaleureux : \r\n(1) Le caméscope est conçu pour les amateurs, pas pour la photographie professionnelle. \r\n(2) Avant d\'utiliser l\'appareil photo, veuillez formater la carte SD fournie avec l\'appareil photo.', 'assets\\images\\camera19.jpg', '3000', ''),
(30, 'Digit', '- digital_storage_capacity: 8.0 MB;\r\n- digital_zoom: 6.0 multiplier_x; max_focal_length: 108.0 millimeters; optical_zoom: 4.0 multiplier_x\r\n\r\n- Méthode de flash: Interne.Modes de flash: Auto, atténuation des yeux rouges, flash forcé, pas de flash, synchro lente, atténuation des yeux rouges + synchro lente Plage de prise de vue: (grand angle) env. 0,3 m à 5,2 m (ISO800); (Télé) Env. 0,5 m à 2,4 m (ISO800)', 'assets\\images\\camera20.jpg', '3000', ''),
(31, 'Eclipse', '- Appareil photo numérique 2.7K 48MP à pixels élevés: \r\nCet appareil photo numérique peut enregistrer des vidéos jusqu\'à une résolution de 2,7K / 20 FPS et des images de 48,0 MP. \r\n\r\n- Cet appareil photo prend également en charge le zoom avant ou le zoom arrière 4x. Le bouton d\'enregistrement de l\'appareil photo numerique et le bouton de l\'appareil photo sont utilisés séparément. \r\nLe bouton de l\'appareil photo compact est combiné avec le bouton T / W (zoom numérique), ce qui est beaucoup plus pratique.\r\n\r\n- Appareil photo numérique multifonction avec flash intégré: la lampe de poche intégrée de l\'camera peut être allumée ou masquée en fonction de la scène. \r\nVous pouvez également ajuster le réglage ISO pour mieux s\'adapter à un environnement sombre. \r\n\r\n- Cet appareil photo dispose de nombreuses fonctions, notamment Selfie, prise de vue en continu, mise en sourdine à une touche, balance des blancs, horodatage, DISP, la carte d\'extension externe prend en charge jusqu\'à 128 Go de carte SD, etc.\r\n\r\n- Fonction pause et enregistrement pendant la charge: l\'appareil photo compact est livré avec une batterie rechargeable. \r\nL\'appareil photo numerique prend également en charge l\'enregistrement pendant le chargement, ce qui est très approprié pour la prise de vue à long terme. \r\n\r\n- Vous pouvez mettre la vidéo en pause en appuyant sur \"OK\", puis appuyez sur \"OK\" pour continuer l\'enregistrement de la vidéo. Le mode photo et vidéo propose également 8 sélections de scènes et 16 effets de filtre intéressants.\r\n\r\n- Fonction microphone et webcam intégrés: Cette appareil photo compact numérique a un microphone et un haut-parleur intégrés. \r\nCet camera video youtube peut être utilisé comme webcam en le connectant via USB à votre ordinateur. \r\nAppuyez sur \"MODE\" et sélectionnez le mode \"PC CAM\" pour la diffusion en temps réel. \r\n\r\n- Vous pouvez également transférer des fichiers de l\'camera youtube vers un ordinateur via le câble USB inclus.\r\n\r\n- Le cadeau parfait et l\'assurance qualité: cet appareil photo est le cadeau parfait pour les adultes, les personnes âgées, les enfants et les débutants. L\'appareil photo numérique dispose également d\'un filetage de trépied standard ¼ (non inclus). \r\n\r\n- Nous offrons une garantie d\'un an pour cet appareil photo. \r\nSi vous avez des questions, n\'hésitez pas à nous contacter, nous nous efforcerons de vous fournir la meilleure solution dans les 24 heures.', 'assets\\images\\camera21.jpg', '3000', ''),
(32, 'Uno', '- 36MP& 1080 HD：\r\nL\'appareil photo numérique a 36 mégapixels, peut photographier des vidéos ultra-claires 1080P, un zoom numérique 16x, un écran de 2,4 pouces, peut capturer des moments impressionnants pour les enfants en haute définition, pour les enfants Laissez les beaux moments et apportez-leur plus de plaisir.\r\n\r\n- Mode anti-secousse：\r\nLes appareils photo compacts sont équipés d\'un mode anti-tremblement. \r\nAfin d\'éviter que le bougé de l\'appareil photo n\'affecte l\'image claire, la structure est spécialement conçue pour les enfants en fonction de leur utilisation; dans le processus de photographie, les enfants peuvent également conserver une bonne clarté lors de la prise de vue tout en jouant.\r\n\r\n- Mode de détection de visage：\r\nC\'est un appareil photo intelligent et pratique pour les enfants. \r\nIl ne nécessite pas de compétences élevées en photographie et convient aux adultes / seniors / enfants. \r\nEn cours d\'utilisation, la caméra de poche dispose d\'un mode de détection de visage et d\'un mode de détection de sourire, qui peuvent clairement capturer un bon moment, ne vous inquiétez pas si vous ne pouvez pas bien utiliser la caméra.\r\n\r\n- Facile à porter：\r\nCet appareil photo numérique intelligent a une taille compacte et est pratique pour les enfants à transporter. \r\nLes enfants peuvent se tenir autour du cou et les transporter, sortir jouer, pique-niquer et éclairer le parc d\'attractions. \r\nIls peuvent être portés légèrement sans alourdir les enfants et peuvent être joués facilement.\r\n\r\n- Cultivez vos loisirs：\r\nCe petit appareil photo de poche dispose d\'une puissante fonction d\'appareil photo ultra-claire, qui permet de cultiver le passe-temps de la photographie pour enfants.\r\nLes enfants ont des caméras qui peuvent capturer et enregistrer les moments importants de la journée.', 'assets\\images\\camera22.jpg', '3000', ''),
(33, 'Xampp', '- Appareil photo numérique 48MP avec carte SD 32GB : \r\nCet appareil photo numérique de 48MP peut vous fournir une image ultra haute résolution à chaque prise de vue afin que vous puissiez capturer chaque moment merveilleux. \r\nL\'écran TFT lumineux de 2,7 pouces vous permet de regarder vos photos avec une grande clarté. \r\nAppareil photo numérique équipé d\'une carte mémoire de 32 Go. \r\nVeuillez formater la carte après avoir reçu l\'appareil photo numérique, puis vous pouvez commencer à prendre des photos.\r\n\r\n- Appareil photo compact 2,7 K : avec la résolution vidéo Full HD 2,7 K de l\'appareil photo numérique, vous pouvez enregistrer dans la meilleure qualité et geler à tout moment pour ne rien manquer. \r\nL\'appareil photo est équipé de deux batteries lithium-ion rechargeables. Chaque batterie peut enregistrer jusqu\'à 60 minutes à pleine charge. Cet appareil photo numérique est très léger et compact, ce qui vous permet de l\'emmener partout avec vous.\r\n\r\n- Appareils photo numériques avec zoom 16X : cet appareil photo compact dispose d\'une fonction zoom numérique jusqu\'à 16X. \r\nQue vous fassiez des photos panoramiques ou des gros plans, il vous suffit d\'appuyer sur le bouton \"W/T\" situé à côté de l\'écran pour zoomer à l\'intérieur ou à l\'extérieur et enregistrer chaque détail en haute définition. \r\nSur la partie inférieure de l\'appareil photo se trouve une prise trépied qui prend en charge l\'installation d\'un trépied de 1/4\" de diamètre (trépied non inclus).\r\n\r\n- Appareil photo numérique multifonction : \r\nCet appareil photo compact dispose de nombreuses fonctions intéressantes : 3 prises de vue continue, détection de visages, protection contre les vibrations, prise de vue en accéléré. L\'appareil photo contient également 4 effets spéciaux pour la prise de vue : standard, rétro, noir et blanc, saturation élevée. Vous pouvez changer librement en fonction de la scène. Vous n\'avez pas à vous soucier de la faible luminosité de la nuit. La fonction flash de cet appareil photo numérique éclaircit la scène avec facilité.\r\n\r\n- Téléchargement facile : la date d\'enregistrement peut être réglée sur les photos, vous n\'avez plus à vous soucier d\'oublier le temps de prendre des photos. Le port USB de l\'appareil photo numérique vous permet de transférer facilement des données vers votre appareil. \r\n\r\nChacune de vos photos devient un souvenir unique et durable. Cette caméra est facile à utiliser et à naviguer, ce qui en fait un cadeau parfait pour les enfants/amis/famille.', 'assets\\images\\camera23.jpg', '3000', ''),
(34, 'Discovery', '- Appareil photo numérique à visée et prise de vue avec des fonctions riches. Écran LCD TFT 2,8 \", photos 16MP et vidéos FHD 1080p, batterie 1050 mah (fonctionne environ 2-3 heures après une charge complète).\r\n\r\n- Caméra numérique étanche pour enfants, jusqu\'à une profondeur maximale de 16FT / 5M sous l\'eau. \r\nConception compacte, aucun boîtier supplémentaire n\'est nécessaire.\r\n \r\n- Caméra sous-marine parfaite pour la natation, la plongée en apnée, la plongée. Profitez de l\'été, capturez le temps amusant de l\'eau des enfants.\r\nConception légère et appareil photo étanche de petite taille, facile à utiliser. \r\nIl est portable pour prendre des photos pour des moments heureux.\r\n\r\n- Appareil photo débutant pour enfants, adolescents, étudiants, personnes âgées. Grand cadeau pour eux d\'explorer le monde avec un appareil photo. Pour les amateurs uniquement, pas pour les utilisateurs professionnels.\r\n\r\n- Cette caméra étanche nécessite jusqu\'à 32 Go de carte Micro SD externe (non incluse). La classe 10 est fortement recommandée. \r\nVeuillez le commander séparément.', 'assets\\images\\camera24.jpg', '3000', ''),
(35, 'Data', '- De près comme de loin immortalisez chaque instant précieux avec une qualité exceptionnelle grâce à cet appareil photo\r\nObtenez des images exceptionnelles grâce à la résolution de 20 millions de pixels.\r\n\r\nIl vous suffit de cadrer et déclencher pour obtenir des résultats exceptionnels.\r\n\r\nAppareil photo numérique IXUS185; Dragonne WS-800; BatterieNB-11L; Chargeur de batterieCB-2LFE; Câble secteur; Kit du manuel de l\'utilisateur.', 'assets\\images\\camera25.jpg', '3000', ''),
(36, 'Intel', '- Impression à un Bouton Appareil Photo Numériques:\r\nL\'imprimanteeIl suffit de viser et de photographier pour que les enfants obtiennent leurs photos et partagent leurs souvenirs en quelques secondes après avoir appuyé sur le bouton d\'impression，Les images en noir et blanc sont imprimées sur du papier photo écologique,Laissez vos jeunes donner vie à leur créativité et colorant les photos imprimées avec les stylos de couleur inclus. \r\nFacile à utiliser,économique à posséder, parfait pour les enfants.\r\n\r\n- Appareil photo pour enfants，Qualité premium: \r\nMatériau ABS de haute qualité, résistant aux chocs, non toxiques et écologiques, sans danger pour les enfants.\r\nLa caméra portable aide les enfants à découvrir et explorer des inconnus, dépeindre les moments heureux dans leurs yeux. \r\nLes parents peuvent apprendre aux enfants à prendre la photo, profitant du temps d\'interaction parent-enfant.\r\n\r\n- Fonctions Riches ,32G Haute Capacité:\r\nHaute capacité de 32 Go: Conception haute configuration Pixels HD, vidéos 1080P, batterie rechargeable 1200mAh, peut être prise 2000+ photos ou vidéo pendant 2 heures, impression durable de 400 photos.\r\n20 cadres amusants permettent aux enfants de modifier la photo en utilisant leur créativité pour obtenir le résultat souhaité.\r\ndans une batterie au lithium rechargeable de 1000 mAh, lorsque les enfants prennent l\'appareil photo des enfants, il suffit de coller la clé de l\'interrupteur, votre tout-petit s\'amuse pendant des heures derrière l\'appareil photo. y compris appareil photo * 1, cordon * 1, rouleau de papier d\'impression * 3, stylo de couleur * 5.\r\n\r\n- Effets de Caméra plus Amusants:\r\nGrand cadeau de festival pour les enfants: ce produit n\'est pas seulement un jouet pour enfants, mais aussi un véritable appareil photo. \r\nIl peut éloigner les enfants des téléphones portables et les aider à découvrir le monde. \r\nCe serait le meilleur cadeau d\'anniversaire pour Noël, le nouvel an, Vacances, anniversaire，les fêtes pour les enfants 3-12 ans.\r\nEmballage exquis, adapté à un usage personnel et aux cadeaux.', 'assets\\images\\camera26.jpg', '3000', ''),
(37, 'Cloud', '- QUALITE D\'IMAGE A COUPER LE SOUFFLE : Capteur CMOS Exmor RS empilé de type 1.0 d\'une résolution de 20,1 mégapixels, et doté de la technologie de rétroéclairage pour atteindre une large couverture de sensibilités.\r\n\r\n- IDEAL POUR LES VIDEASTES : Stabilisation d\'image et écran inclinable/selfie pour créer vos vlogs.\r\n\r\n- CAPTUREZ LES MOMENTS DECISIFS : Viseur électronique OLED Tru-Finder intégré pour un confort de prise en main apprécié de tous les photographes avertis.\r\n\r\n- PARTAGEZ VOS CREATIONS : Diffusez vos contenus depuis vos appareils mobiles facilement grâce à l\'application Imaging Edge Mobile(Wi-Fi).\r\n\r\n- DANS LE CADRE : Cadrez facilement vos sujets sous différents angles de vue grâce à l\'écran orientable.\r\n\r\nREMARQUE : Les piles sont incluses.', 'assets\\images\\camera27.jpg', '3000', ''),
(38, 'Cosmique', '- Appareil photo numérique FHD 2,7 K et 44 MP : \r\nCet appareil photo numérique avec enregistrement vidéo Ultra HD 2.7K et 44.0 mégapixels vous aidera à capturer des moments merveilleux et inoubliables en capturant des photos ou des vidéos de qualité supérieure et nettes. \r\nVous pouvez toujours utiliser ce mini appareil photo compact pour enregistrer des moments de plaisir avec des amis, des membres de la famille et des camarades de classe.\r\n\r\n- Zoom numérique 16 x et lumière d\'éclaircissement : Cet appareil photo numérique est équipé d\'un zoom numérique 16 x, vous pouvez appuyer sur le bouton W / T pour réduire ou réduire les objets distants et capturer tous les détails que vous avez faits. \r\nCe sac pour appareil photo numérique avec microphone intégré peut enregistrer votre propre voix, et vous pouvez également utiliser la lumière intégrée pour vous aider à prendre des photos en cas de faible luminosité.\r\n\r\n- Webcam et enregistrement de vlogging : cette caméra numérique pour enfants peut être utilisée comme webcam, de sorte que vous pouvez profiter de conversations vidéo ou de streaming en temps réel.\r\n- Connectez l\'appareil photo numérique rechargeable à votre ordinateur via un câble USB pour passer des conversations vidéo en famille ou entre amis.\r\n\r\n- Vous pouvez non seulement les utiliser pour des transferts en direct de haute qualité sur YouTube, Facebook, Twitter ou d\'autres médias sociaux, mais aussi partager vos photos et vidéos de votre appareil photo.\r\n\r\n- Appareil photo numérique multifonction : Cet appareil photo numérique prend en charge les fonctions anti-shake, détection des ages, capture sourire, flash continu, auto-extinction, fonction Beauty Face, simple de quitter un moment de plaisir, font de chaque age un précieux souvenir. \r\nCe it appareil photo numérique est certainement un partenaire de voyage parfait pour vous pour enregistrer les merveilleux moments de votre , saisir et marcher sans vous soucier de transporter du matériel lourd.\r\n\r\n- Portable et facile à utiliser : cet appareil photo numérique portable pour enfants est très léger et it, facile à utiliser et à mettre dans la poche pour l\'emporter partout et à tout moment.\r\n\r\nUn cadeau parfait pour les enfants, les adolescents, les photographies, les étudiants, les personnes âgées. \r\nLe meilleur choix pour Noël, Thanksgiving, cadeaux d\'anniversaire. Nous offrons une de 1 an, chaque problème est contactez-nous, nous vous enverrons une longueur satisfaisante dans les 24 heures.', 'assets\\images\\camera28.jpg', '3000', ''),
(39, 'View', '- Appareil Photo Numérique\r\n- Zoom Optique 25X\r\n- Zoom numérique: 4X\r\n- Capteur CCD de 16 millions de pixels\r\n- Ecran LCD de 3 pouces', 'assets\\images\\camera29.jpg', '3000', ''),
(40, 'Label', '- Fait de matériaux de bonne qualité, robuste et durable.Alimenté par 3 * piles AAA, facile à utiliser.\r\n\r\n- Un capteur supérieur garantit des photos 2 MP et des vidéos 720P, la cadence est de 30 images par seconde, peut vous aider à capturer tout moment précieux et éphémère.\r\n\r\n- Facile à utiliser, avec de nombreuses fonctions utiles telles que zoom numérique 4X, lumière de remplissage.\r\nLe grand écran 2,4 pouces vous permet de regarder la lecture avec des images haute définition.\r\n\r\n- Taille compacte et légère, facile à transporter et à ranger.', 'assets\\images\\camera30.jpg', '3000', ''),
(41, 'Oxford', '- Capteur CMOS, TFT, zoom numérique 8 fois.\r\n\r\n- Mini et portable, simple, avec prise de vue, caméra audio, suivi du visage, stabilisation d\'image électronique et d\'autres fonctions.\r\n\r\n- Balance des blancs : automatique, jour, nuageux, tungstène, lampe fluorescente.\r\nScène : automatique, portrait de nuit, vue de nuit, portrait, paysage, mouvement.\r\n\r\n- Langues de fonctionnement : chinois simplifié, chinois traditionnel, anglais, français, espagnol, portugais, etc.', 'assets\\images\\camera31.jpg', '3000', ''),
(42, 'Smily', '- Appareil Photo Numériques FHD 2.7K & 44MP: \r\nCet Appareil Photo Numérique dispose d\'une technologie optique puissante, d\'une résolution vidéo Ultra HD 2.7K et d\'une résolution d\'image de 44,0 mégapixels pour capturer les moments les plus excitants avec une meilleure qualité d\'image ou de vidéo. \r\nÉcran LCD de 2,8 pouces, vous pouvez toujours utiliser ce mini Appareil Photo Compact pour enregistrer des moments amusants avec des amis, des membres de la famille et des enfants.\r\n\r\n- Appareil Photo Numérique avec Webcam Fonction: \r\nCet Appareil Photo Numerique pour enfants peut être utilisé comme webcam, afin que vous puissiez profiter du chat vidéo ou du streaming en temps réel. Vous pouvez utiliser l\'USB pour fournir une diffusion en direct de haute qualité sur YouTube, Facebook, Twitter ou d\'autres médias sociaux, ou transférer des photos et des vidéos de l\'appareil photo vers votre ordinateur, puis partager vos belles photos et vidéos pour médias sociaux.\r\n\r\n- Appareil Photo Numériques avec Zoom Numérique 16X et flash LED: \r\nCet Appareil Photo Numérique est équipé d\'un Zoom Numérique 16X, vous pouvez appuyer sur le bouton W/T pour zoomer ou dézoomer sur des objets distants et capturer tous les détails dont vous avez besoin. \r\nCet Appareil Photo Numérique pas cher a une fonction anti-tremblement, l\'image vidéo est plus stable et la lumière de remplissage intégrée vous aide à prendre des photos de qualité dans l\'obscurité.\r\n\r\n- Appareil Photo Compact avec Retardateur et Fonction de Capture de Sourire: \r\ncet Appareil Photo pour Enfants a une Fonction d\'accéléré, le temps de retard peut être réglé sur 2 s, 5 s ou 10 s, vous donnant suffisamment de temps pour prendre des photos ou des vidéos. Pendant l\'utilisation, l\'appareils Photo Numériques dispose de modes de reconnaissance faciale et de beauté du visage, qui peuvent capturer clairement de beaux moments sans se soucier de manquer des moments heureux.\r\n\r\n- Portable et facile à utiliser: \r\nCet Appareils Photo Numériques pour enfants est très léger et petit, facile à utiliser et à mettre dans votre poche pour l\'emporter avec vous à tout moment et n\'importe où. \r\nUn cadeau parfait pour les enfants, les adolescents, les débutants en photographie, les personnes âgées.\r\n \r\nSi vous rencontrez des problèmes lors de l\'utilisation, veuillez nous contacter à temps, nous vous fournirons une solution satisfaisante dans les 24 heures (Bonus : deux piles).', 'assets\\images\\camera32.jpg', '3000', '');
INSERT INTO `product` (`id`, `title`, `description`, `image`, `price`, `short_description`) VALUES
(43, 'Info', '- UNE QUALITE D\'IMAGE UNIQUE : Grand capteur MOS type 1 pouce 20,1MP pour des photos aux couleurs riches et détaillées.\r\n\r\n- Stabilisation Hybrid O.I.S. 5 axes pour des images nettes, même à main levée.\r\n\r\n- UN OBJECTIF ULTRA POLYVALENT : Zoom LEICA DC Vario-Elmar 15x (24-360mm) pour aller au plus près du sujet - Ouverture F3.3 - 6.4.\r\n\r\n- DES FONCTIONS EXPERTES : Vidéo 4K 30p / Full HD 60p - Photo 4K pour réaliser une rafale de 30 i/s et capturer l\'instant parfait - Fonction Post Focus afin de vous concentrer sur la prise de vue et faire la mise au point plus tard\r\nUNE RAPIDITE ULTIME : Rafale 6 i/s (AFC) et 10 i/s (AFS) - Autofocus ultra rapide DFD 49 collimateurs.\r\n\r\n- UNE UTILISATION INTUITIVE : Viseur Électronique Haute Résolution 2330K pts (grossissement env. 0.53x) pour un cadrage confortable et précis - Écran LCD 3.0“ 1240K pts tactile - Autonomie 370 photos environ - Flash intégré - Connectivité WiFi & Bluetooth', 'assets\\images\\camera33.jpg', '11', ''),
(44, 'Card', '- Réactif et intuitif dès que vous le prenez en main avec sa prise de vue en rafale à 30 im./s. et sa mise au point automatique rapide, le tout alimenté par un processeur DIGIC 8.\r\n\r\n- Appareil photo numérique PowerShot G7 X Mark III noir Dragonne WS-DC12 Batterie NB-13L.\r\n\r\n- Chargeur de batterie CB-2LHE Câble secteur Manuel d\'utilisation.', 'assets\\images\\camera34.jpg', '11', ''),
(45, 'Board', '                        - Appareil photo Bridge\r\n- Zoom optique 52x\r\n- Grand angle de 24 mm.\r\n- 16 MP CMOS\r\n- Prise de vue en rafale de 6 fps\r\n- LCD de 3\".\r\n- Connexion Wi-Fi\r\n- Contrôle sans fil avec votre appareil iOS TM.\r\n                ', 'assets\\images\\camera45.jpg', '0', 'dslldslds');

-- --------------------------------------------------------

--
-- Structure de la table `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `login` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Déchargement des données de la table `user`
--

INSERT INTO `user` (`id`, `login`, `password`) VALUES
(1, 'admin', '$2y$10$Mjnzm6KGMH3O.qrlxlbJ3eVv0B3/uPYQBT1bpYddVc.I5iE/bWULa');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `comment`
--
ALTER TABLE `comment`
  ADD KEY `product_id` (`product_id`);

--
-- Index pour la table `order`
--
ALTER TABLE `order`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `order`
--
ALTER TABLE `order`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT pour la table `product`
--
ALTER TABLE `product`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=46;

--
-- AUTO_INCREMENT pour la table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `comment`
--
ALTER TABLE `comment`
  ADD CONSTRAINT `comment_ibfk_1` FOREIGN KEY (`product_id`) REFERENCES `product` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;
